"""Provider-neutral contracts used by the voice companion service."""

from __future__ import annotations

from collections.abc import AsyncIterator
from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True, slots=True)
class TranscriptionResult:
    """Normalized result returned by an STT provider."""

    text: str
    language: str | None = None
    duration_seconds: float | None = None


@dataclass(frozen=True, slots=True)
class AudioResult:
    """In-memory audio generated by a TTS provider."""

    data: bytes
    content_type: str


class SpeechToTextProvider(Protocol):
    """Transcribe audio without exposing a vendor in the runtime."""

    async def transcribe(
        self,
        audio: bytes,
        *,
        content_type: str,
        language: str | None = None,
    ) -> TranscriptionResult:
        """Return a normalized transcript for supplied audio."""
        ...


class TextToSpeechProvider(Protocol):
    """Synthesize and stream speech without coupling to a vendor SDK."""

    async def synthesize(
        self,
        text: str,
        *,
        voice: str | None = None,
        language: str | None = None,
    ) -> AudioResult:
        """Create an in-memory audio response."""
        ...

    def stream(
        self,
        text: str,
        *,
        voice: str | None = None,
        language: str | None = None,
    ) -> AsyncIterator[bytes]:
        """Yield audio chunks as they become available."""
        ...
